# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

$nginx_install = <<SCRIPT
  apt-get update && apt-get upgrade
  if [ ! -x /usr/sbin/nginx ]; then
    apt-get install -y nginx;
  fi
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "web" do |web|
    web.vm.box = "generic/debian12"
    web.vm.network :public_network
    #web.vm.provision "shell", inline: "echo 'Connecté en bridge' > /etc/motd"
    web.vm.provision "shell", inline: $nginx_install
  end
end
