# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

$nginx_install = <<SCRIPT
  apt-get update && apt-get upgrade
  if [ ! -x /usr/sbin/nginx ]; then
    apt-get install -y nginx;
  fi
  ln -s /opt/vagrantsite /usr/share/nginx/html/vagrantsite
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "web", primary: true do |web|
    web.vm.box ="generic/debian12"
    web.vm.network "forwarded_port", guest:80, host:8888
    web.vm.synced_folder "vagrantsite/", "/opt/vagrantsite"
    web.vm.provision "shell", inline: $nginx_install
    web.vm.provider "virtualbox" do |vbox|
      vbox.memory = 2048
      vbox.cpus = 2
    end
  end
end
