# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "database" do |db|
    db.vm.box = "generic/debian12"
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "10.0.2.10", virtualbox__intnet: "NatNetwork"
  end
  config.vm.define "web" do |web|
    web.vm.box = "generic/debian12"
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip:"10.0.2.11", virtualbox__intnet: "NatNetwork"
  end
end
